### ISSUE TITLE
Concrete representation terminology

### ISSUE THREAD

**Issue by ralphfreese** [UniversalAlgebra/fin-lat-rep#8]
This is somewhat confusing. What I think is best for the two notions is

  representations of finite lattices as congruence lattices of a finite
  algebra

  representations of finite lattices as lattices of equivalence relations
  on a finite set

The first is most important for us and we abbreviate it to just
representation of L.  But I think we should use the second (or a
shortening of it) in place of "concrete representation."

The concrete representation problem (is a sublattice of Eq X a congruence
lattice where it sits) still makes sense.

Unlike changing the diagram, which naturally was assigned to William, this
should be assigned to all of us, ie., whoever gets to it first.

**Comment by williamdemeo** [comment]
Okay, I can address this.  It might help to make this clearer if we use some special symbols to denote these ideas.  What I was already planning to propose is that we adopt conventions used by Berman in his thesis (I think he attributes some of this notation to Gratzer).  We can define the following classes (probably script L's would be better, but I don't know how to do that in markdown):
- L<sub>0</sub> = all finite lattices
- L<sub>1</sub> = lattices iso. to sublattices of finite partition lattices
- L<sub>2</sub> = lattices iso. to strong congruence lattices of finite partial algebras
- L<sub>3</sub> = lattices iso. to congruence lattices of finite algebras
- L<sub>4</sub> = lattices iso. to intervals in subgroup lattices of finite groups
- L<sub>5</sub> = lattices iso. to subgroup lattices of finite groups

This notation makes it easier to explain exactly what problem(s) we're trying to solve, and also will help to clarify the distinction you described above.

In particular, what I think you're saying is that the "representable" lattices are exactly the ones belonging to L<sub>3</sub>, while the lattices in L<sub>1</sub> are those with a "concrete representation".

Also, with this notation, we can easily describe relations among these classes. For example,
- L<sub>0</sub> \supseteq L<sub>1</sub> \supseteq ... \supseteq L<sub>5</sub>.
- L<sub>0</sub> = L<sub>1</sub> (Pudlak-Tuma)
- L<sub>0</sub> = L<sub>3</sub> if and only if L<sub>0</sub> = L<sub>4</sub> (Palfy-Pudlak)

**Comment by ralphfreese** [comment]
This might be good (but it might be more than we need). What Bjarni meant by concrete representation is not
- L<sub>1</sub> = lattices iso. to sublattices of finite partition lattices,
  but
- L'<sub>1</sub> = sublattices of finite partition lattices

that is, lattices whose universe is a set of partitions with the join and meet form Eq X. Of course this is the class of closed, in our sense, sublattices of Eq X.

**Comment by williamdemeo** [comment]
I revised the intro to the section (currently Sec 3) where this is discussed.  It didn't need much (maybe someone already helped with this?)  It seems perfectly clear to me, so I'll close this issue.  Feel free to reopen it if you think it's still unclear.
